/*
 * generated by Xtext
 */
package org.xtext.activity.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ActUiModule extends org.xtext.activity.ui.AbstractActUiModule {
	public ActUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
