/*
 * generated by Xtext
 */
package org.xtext.launcher.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class StartUiModule extends org.xtext.launcher.ui.AbstractStartUiModule {
	public StartUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
