/*
 * generated by Xtext
 */
package org.xtext.launcher.ui.contentassist

import org.xtext.launcher.ui.contentassist.AbstractStartProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class StartProposalProvider extends AbstractStartProposalProvider {
}
