/*
* generated by Xtext
*/
package org.xtext.launcher;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class StartUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.launcher.ui.internal.StartActivator.getInstance().getInjector("org.xtext.launcher.Start");
	}
	
}
