/*
* generated by Xtext
*/
package org.xtext.activity.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class ActGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cModelAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cCategorieKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cActivityAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cActivityPeriodicActivityParserRuleCall_4_0 = (RuleCall)cActivityAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Model:
		//	{Model} "Categorie" name=EString "{" activity+=PeriodicActivity* "}";
		public ParserRule getRule() { return rule; }

		//{Model} "Categorie" name=EString "{" activity+=PeriodicActivity* "}"
		public Group getGroup() { return cGroup; }

		//{Model}
		public Action getModelAction_0() { return cModelAction_0; }

		//"Categorie"
		public Keyword getCategorieKeyword_1() { return cCategorieKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//activity+=PeriodicActivity*
		public Assignment getActivityAssignment_4() { return cActivityAssignment_4; }

		//PeriodicActivity
		public RuleCall getActivityPeriodicActivityParserRuleCall_4_0() { return cActivityPeriodicActivityParserRuleCall_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class PeriodicActivityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PeriodicActivity");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPeriodicActivityAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cPeriodicActivityKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cWorkshopKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cAtelierAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cAtelierAtelierCrossReference_4_1_0 = (CrossReference)cAtelierAssignment_4_1.eContents().get(0);
		private final RuleCall cAtelierAtelierEStringParserRuleCall_4_1_0_1 = (RuleCall)cAtelierAtelierCrossReference_4_1_0.eContents().get(1);
		private final Keyword cCommaKeyword_4_2 = (Keyword)cGroup_4.eContents().get(2);
		private final Keyword cFromKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cStartAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cStartDateParserRuleCall_6_0 = (RuleCall)cStartAssignment_6.eContents().get(0);
		private final Keyword cToKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cEndAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cEndDateParserRuleCall_8_0 = (RuleCall)cEndAssignment_8.eContents().get(0);
		private final Keyword cCommaKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cEveryKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cFrequencyAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cFrequencyEIntParserRuleCall_10_1_0 = (RuleCall)cFrequencyAssignment_10_1.eContents().get(0);
		private final Assignment cPeriodicityTypeAssignment_10_2 = (Assignment)cGroup_10.eContents().get(2);
		private final RuleCall cPeriodicityTypePeriodicityEnumRuleCall_10_2_0 = (RuleCall)cPeriodicityTypeAssignment_10_2.eContents().get(0);
		private final Keyword cCommaKeyword_10_3 = (Keyword)cGroup_10.eContents().get(3);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cAllocateKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_11_1 = (Keyword)cGroup_11.eContents().get(1);
		private final Assignment cResAllocationAssignment_11_2 = (Assignment)cGroup_11.eContents().get(2);
		private final RuleCall cResAllocationResAllocationParserRuleCall_11_2_0 = (RuleCall)cResAllocationAssignment_11_2.eContents().get(0);
		private final Group cGroup_11_3 = (Group)cGroup_11.eContents().get(3);
		private final Keyword cCommaKeyword_11_3_0 = (Keyword)cGroup_11_3.eContents().get(0);
		private final Assignment cResAllocationAssignment_11_3_1 = (Assignment)cGroup_11_3.eContents().get(1);
		private final RuleCall cResAllocationResAllocationParserRuleCall_11_3_1_0 = (RuleCall)cResAllocationAssignment_11_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11_4 = (Keyword)cGroup_11.eContents().get(4);
		private final Keyword cCommaKeyword_11_5 = (Keyword)cGroup_11.eContents().get(5);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cRulesKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_12_1 = (Keyword)cGroup_12.eContents().get(1);
		private final Assignment cRuleAssignment_12_2 = (Assignment)cGroup_12.eContents().get(2);
		private final RuleCall cRuleRuleParserRuleCall_12_2_0 = (RuleCall)cRuleAssignment_12_2.eContents().get(0);
		private final Group cGroup_12_3 = (Group)cGroup_12.eContents().get(3);
		private final Keyword cCommaKeyword_12_3_0 = (Keyword)cGroup_12_3.eContents().get(0);
		private final Assignment cRuleAssignment_12_3_1 = (Assignment)cGroup_12_3.eContents().get(1);
		private final RuleCall cRuleRuleParserRuleCall_12_3_1_0 = (RuleCall)cRuleAssignment_12_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_12_4 = (Keyword)cGroup_12.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//PeriodicActivity:
		//	{PeriodicActivity} "PeriodicActivity" name=EString "{" ("workshop" atelier=[exploitation::Atelier|EString] ",")?
		//	"from" start=Date "to" end=Date "," ("every" frequency=EInt? periodicityType=Periodicity ",")? ("allocate" "{"
		//	resAllocation+=ResAllocation ("," resAllocation+=ResAllocation)* "}" ",")? ("rules" "{" rule+=Rule ("," rule+=Rule)*
		//	"}")? "}";
		public ParserRule getRule() { return rule; }

		//{PeriodicActivity} "PeriodicActivity" name=EString "{" ("workshop" atelier=[exploitation::Atelier|EString] ",")? "from"
		//start=Date "to" end=Date "," ("every" frequency=EInt? periodicityType=Periodicity ",")? ("allocate" "{"
		//resAllocation+=ResAllocation ("," resAllocation+=ResAllocation)* "}" ",")? ("rules" "{" rule+=Rule ("," rule+=Rule)*
		//"}")? "}"
		public Group getGroup() { return cGroup; }

		//{PeriodicActivity}
		public Action getPeriodicActivityAction_0() { return cPeriodicActivityAction_0; }

		//"PeriodicActivity"
		public Keyword getPeriodicActivityKeyword_1() { return cPeriodicActivityKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("workshop" atelier=[exploitation::Atelier|EString] ",")?
		public Group getGroup_4() { return cGroup_4; }

		//"workshop"
		public Keyword getWorkshopKeyword_4_0() { return cWorkshopKeyword_4_0; }

		//atelier=[exploitation::Atelier|EString]
		public Assignment getAtelierAssignment_4_1() { return cAtelierAssignment_4_1; }

		//[exploitation::Atelier|EString]
		public CrossReference getAtelierAtelierCrossReference_4_1_0() { return cAtelierAtelierCrossReference_4_1_0; }

		//EString
		public RuleCall getAtelierAtelierEStringParserRuleCall_4_1_0_1() { return cAtelierAtelierEStringParserRuleCall_4_1_0_1; }

		//","
		public Keyword getCommaKeyword_4_2() { return cCommaKeyword_4_2; }

		//"from"
		public Keyword getFromKeyword_5() { return cFromKeyword_5; }

		//start=Date
		public Assignment getStartAssignment_6() { return cStartAssignment_6; }

		//Date
		public RuleCall getStartDateParserRuleCall_6_0() { return cStartDateParserRuleCall_6_0; }

		//"to"
		public Keyword getToKeyword_7() { return cToKeyword_7; }

		//end=Date
		public Assignment getEndAssignment_8() { return cEndAssignment_8; }

		//Date
		public RuleCall getEndDateParserRuleCall_8_0() { return cEndDateParserRuleCall_8_0; }

		//","
		public Keyword getCommaKeyword_9() { return cCommaKeyword_9; }

		//("every" frequency=EInt? periodicityType=Periodicity ",")?
		public Group getGroup_10() { return cGroup_10; }

		//"every"
		public Keyword getEveryKeyword_10_0() { return cEveryKeyword_10_0; }

		//frequency=EInt?
		public Assignment getFrequencyAssignment_10_1() { return cFrequencyAssignment_10_1; }

		//EInt
		public RuleCall getFrequencyEIntParserRuleCall_10_1_0() { return cFrequencyEIntParserRuleCall_10_1_0; }

		//periodicityType=Periodicity
		public Assignment getPeriodicityTypeAssignment_10_2() { return cPeriodicityTypeAssignment_10_2; }

		//Periodicity
		public RuleCall getPeriodicityTypePeriodicityEnumRuleCall_10_2_0() { return cPeriodicityTypePeriodicityEnumRuleCall_10_2_0; }

		//","
		public Keyword getCommaKeyword_10_3() { return cCommaKeyword_10_3; }

		//("allocate" "{" resAllocation+=ResAllocation ("," resAllocation+=ResAllocation)* "}" ",")?
		public Group getGroup_11() { return cGroup_11; }

		//"allocate"
		public Keyword getAllocateKeyword_11_0() { return cAllocateKeyword_11_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_11_1() { return cLeftCurlyBracketKeyword_11_1; }

		//resAllocation+=ResAllocation
		public Assignment getResAllocationAssignment_11_2() { return cResAllocationAssignment_11_2; }

		//ResAllocation
		public RuleCall getResAllocationResAllocationParserRuleCall_11_2_0() { return cResAllocationResAllocationParserRuleCall_11_2_0; }

		//("," resAllocation+=ResAllocation)*
		public Group getGroup_11_3() { return cGroup_11_3; }

		//","
		public Keyword getCommaKeyword_11_3_0() { return cCommaKeyword_11_3_0; }

		//resAllocation+=ResAllocation
		public Assignment getResAllocationAssignment_11_3_1() { return cResAllocationAssignment_11_3_1; }

		//ResAllocation
		public RuleCall getResAllocationResAllocationParserRuleCall_11_3_1_0() { return cResAllocationResAllocationParserRuleCall_11_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_11_4() { return cRightCurlyBracketKeyword_11_4; }

		//","
		public Keyword getCommaKeyword_11_5() { return cCommaKeyword_11_5; }

		//("rules" "{" rule+=Rule ("," rule+=Rule)* "}")?
		public Group getGroup_12() { return cGroup_12; }

		//"rules"
		public Keyword getRulesKeyword_12_0() { return cRulesKeyword_12_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_12_1() { return cLeftCurlyBracketKeyword_12_1; }

		//rule+=Rule
		public Assignment getRuleAssignment_12_2() { return cRuleAssignment_12_2; }

		//Rule
		public RuleCall getRuleRuleParserRuleCall_12_2_0() { return cRuleRuleParserRuleCall_12_2_0; }

		//("," rule+=Rule)*
		public Group getGroup_12_3() { return cGroup_12_3; }

		//","
		public Keyword getCommaKeyword_12_3_0() { return cCommaKeyword_12_3_0; }

		//rule+=Rule
		public Assignment getRuleAssignment_12_3_1() { return cRuleAssignment_12_3_1; }

		//Rule
		public RuleCall getRuleRuleParserRuleCall_12_3_1_0() { return cRuleRuleParserRuleCall_12_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_12_4() { return cRightCurlyBracketKeyword_12_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
	}

	public class AtelierElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Atelier");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cAtelier_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cElevageParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cCultureParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Atelier returns exploitation::Atelier:
		//	Atelier_Impl | Elevage | Culture;
		public ParserRule getRule() { return rule; }

		//Atelier_Impl | Elevage | Culture
		public Alternatives getAlternatives() { return cAlternatives; }

		//Atelier_Impl
		public RuleCall getAtelier_ImplParserRuleCall_0() { return cAtelier_ImplParserRuleCall_0; }

		//Elevage
		public RuleCall getElevageParserRuleCall_1() { return cElevageParserRuleCall_1; }

		//Culture
		public RuleCall getCultureParserRuleCall_2() { return cCultureParserRuleCall_2; }
	}

	public class DateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Date");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cDateAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cDayAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cDayEIntParserRuleCall_1_0 = (RuleCall)cDayAssignment_1.eContents().get(0);
		private final Assignment cMonthAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cMonthMonthEnumRuleCall_2_0 = (RuleCall)cMonthAssignment_2.eContents().get(0);
		
		//Date:
		//	{Date} day=EInt month=Month;
		public ParserRule getRule() { return rule; }

		//{Date} day=EInt month=Month
		public Group getGroup() { return cGroup; }

		//{Date}
		public Action getDateAction_0() { return cDateAction_0; }

		//day=EInt
		public Assignment getDayAssignment_1() { return cDayAssignment_1; }

		//EInt
		public RuleCall getDayEIntParserRuleCall_1_0() { return cDayEIntParserRuleCall_1_0; }

		//month=Month
		public Assignment getMonthAssignment_2() { return cMonthAssignment_2; }

		//Month
		public RuleCall getMonthMonthEnumRuleCall_2_0() { return cMonthMonthEnumRuleCall_2_0; }
	}

	public class ResAllocationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ResAllocation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRessourceAllocationAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cReserveKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cRessourceAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cRessourceRessourceCrossReference_2_0 = (CrossReference)cRessourceAssignment_2.eContents().get(0);
		private final RuleCall cRessourceRessourceEStringParserRuleCall_2_0_1 = (RuleCall)cRessourceRessourceCrossReference_2_0.eContents().get(1);
		private final Keyword cForKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cDurationAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDurationEIntParserRuleCall_4_0 = (RuleCall)cDurationAssignment_4.eContents().get(0);
		private final Assignment cPeriodicityTypeAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cPeriodicityTypePeriodicityEnumRuleCall_5_0 = (RuleCall)cPeriodicityTypeAssignment_5.eContents().get(0);
		
		//ResAllocation returns RessourceAllocation:
		//	{RessourceAllocation} "reserve" ressource=[exploitation::Ressource|EString] "for" duration=EInt
		//	periodicityType=Periodicity;
		public ParserRule getRule() { return rule; }

		//{RessourceAllocation} "reserve" ressource=[exploitation::Ressource|EString] "for" duration=EInt
		//periodicityType=Periodicity
		public Group getGroup() { return cGroup; }

		//{RessourceAllocation}
		public Action getRessourceAllocationAction_0() { return cRessourceAllocationAction_0; }

		//"reserve"
		public Keyword getReserveKeyword_1() { return cReserveKeyword_1; }

		//ressource=[exploitation::Ressource|EString]
		public Assignment getRessourceAssignment_2() { return cRessourceAssignment_2; }

		//[exploitation::Ressource|EString]
		public CrossReference getRessourceRessourceCrossReference_2_0() { return cRessourceRessourceCrossReference_2_0; }

		//EString
		public RuleCall getRessourceRessourceEStringParserRuleCall_2_0_1() { return cRessourceRessourceEStringParserRuleCall_2_0_1; }

		//"for"
		public Keyword getForKeyword_3() { return cForKeyword_3; }

		//duration=EInt
		public Assignment getDurationAssignment_4() { return cDurationAssignment_4; }

		//EInt
		public RuleCall getDurationEIntParserRuleCall_4_0() { return cDurationEIntParserRuleCall_4_0; }

		//periodicityType=Periodicity
		public Assignment getPeriodicityTypeAssignment_5() { return cPeriodicityTypeAssignment_5; }

		//Periodicity
		public RuleCall getPeriodicityTypePeriodicityEnumRuleCall_5_0() { return cPeriodicityTypePeriodicityEnumRuleCall_5_0; }
	}

	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//	STRING | ID;
		public ParserRule getRule() { return rule; }

		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}

	public class RuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Rule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRuleAction_0 = (Action)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cPreKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cPreAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cPrePredicateParserRuleCall_1_1_0 = (RuleCall)cPreAssignment_1_1.eContents().get(0);
		private final Group cGroup_1_2 = (Group)cGroup_1.eContents().get(2);
		private final Keyword cCommaKeyword_1_2_0 = (Keyword)cGroup_1_2.eContents().get(0);
		private final Keyword cPreKeyword_1_2_1 = (Keyword)cGroup_1_2.eContents().get(1);
		private final Assignment cPreAssignment_1_2_2 = (Assignment)cGroup_1_2.eContents().get(2);
		private final RuleCall cPrePredicateParserRuleCall_1_2_2_0 = (RuleCall)cPreAssignment_1_2_2.eContents().get(0);
		
		//Rule:
		//	{Rule} ("pre" pre+=Predicate ("," "pre" pre+=Predicate)*)?;
		public ParserRule getRule() { return rule; }

		//{Rule} ("pre" pre+=Predicate ("," "pre" pre+=Predicate)*)?
		public Group getGroup() { return cGroup; }

		//{Rule}
		public Action getRuleAction_0() { return cRuleAction_0; }

		//("pre" pre+=Predicate ("," "pre" pre+=Predicate)*)?
		public Group getGroup_1() { return cGroup_1; }

		//"pre"
		public Keyword getPreKeyword_1_0() { return cPreKeyword_1_0; }

		//pre+=Predicate
		public Assignment getPreAssignment_1_1() { return cPreAssignment_1_1; }

		//Predicate
		public RuleCall getPrePredicateParserRuleCall_1_1_0() { return cPrePredicateParserRuleCall_1_1_0; }

		//("," "pre" pre+=Predicate)*
		public Group getGroup_1_2() { return cGroup_1_2; }

		//","
		public Keyword getCommaKeyword_1_2_0() { return cCommaKeyword_1_2_0; }

		//"pre"
		public Keyword getPreKeyword_1_2_1() { return cPreKeyword_1_2_1; }

		//pre+=Predicate
		public Assignment getPreAssignment_1_2_2() { return cPreAssignment_1_2_2; }

		//Predicate
		public RuleCall getPrePredicateParserRuleCall_1_2_2_0() { return cPrePredicateParserRuleCall_1_2_2_0; }
	}

	public class Atelier_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Atelier_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cAtelierAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cAtelierKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cActivityKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cActivityAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cActivityPeriodicActivityCrossReference_3_1_0 = (CrossReference)cActivityAssignment_3_1.eContents().get(0);
		private final RuleCall cActivityPeriodicActivityEStringParserRuleCall_3_1_0_1 = (RuleCall)cActivityPeriodicActivityCrossReference_3_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Atelier_Impl returns exploitation::Atelier:
		//	{exploitation::Atelier} "Atelier" "{" ("activity" activity+=[PeriodicActivity|EString])? "}";
		public ParserRule getRule() { return rule; }

		//{exploitation::Atelier} "Atelier" "{" ("activity" activity+=[PeriodicActivity|EString])? "}"
		public Group getGroup() { return cGroup; }

		//{exploitation::Atelier}
		public Action getAtelierAction_0() { return cAtelierAction_0; }

		//"Atelier"
		public Keyword getAtelierKeyword_1() { return cAtelierKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("activity" activity+=[PeriodicActivity|EString])?
		public Group getGroup_3() { return cGroup_3; }

		//"activity"
		public Keyword getActivityKeyword_3_0() { return cActivityKeyword_3_0; }

		//activity+=[PeriodicActivity|EString]
		public Assignment getActivityAssignment_3_1() { return cActivityAssignment_3_1; }

		//[PeriodicActivity|EString]
		public CrossReference getActivityPeriodicActivityCrossReference_3_1_0() { return cActivityPeriodicActivityCrossReference_3_1_0; }

		//EString
		public RuleCall getActivityPeriodicActivityEStringParserRuleCall_3_1_0_1() { return cActivityPeriodicActivityEStringParserRuleCall_3_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//	"-"? INT;
		public ParserRule getRule() { return rule; }

		//"-"? INT
		public Group getGroup() { return cGroup; }

		//"-"?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}

	public class RessourceTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "RessourceType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRessourceTypeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRessourceTypeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//RessourceType returns exploitation::RessourceType:
		//	{exploitation::RessourceType} "RessourceType" name=EString;
		public ParserRule getRule() { return rule; }

		//{exploitation::RessourceType} "RessourceType" name=EString
		public Group getGroup() { return cGroup; }

		//{exploitation::RessourceType}
		public Action getRessourceTypeAction_0() { return cRessourceTypeAction_0; }

		//"RessourceType"
		public Keyword getRessourceTypeKeyword_1() { return cRessourceTypeKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}

	public class PredicateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Predicate");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPredicatAction_0 = (Action)cGroup.eContents().get(0);
		private final RuleCall cEStringParserRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//Predicate returns Predicat:
		//	{Predicat} EString;
		public ParserRule getRule() { return rule; }

		//{Predicat} EString
		public Group getGroup() { return cGroup; }

		//{Predicat}
		public Action getPredicatAction_0() { return cPredicatAction_0; }

		//EString
		public RuleCall getEStringParserRuleCall_1() { return cEStringParserRuleCall_1; }
	}

	public class ElevageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Elevage");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cElevageAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cElevageKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cActivityKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cActivityAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cActivityPeriodicActivityCrossReference_3_1_0 = (CrossReference)cActivityAssignment_3_1.eContents().get(0);
		private final RuleCall cActivityPeriodicActivityEStringParserRuleCall_3_1_0_1 = (RuleCall)cActivityPeriodicActivityCrossReference_3_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Elevage returns exploitation::Elevage:
		//	{exploitation::Elevage} "Elevage" "{" ("activity" activity+=[PeriodicActivity|EString])? "}";
		public ParserRule getRule() { return rule; }

		//{exploitation::Elevage} "Elevage" "{" ("activity" activity+=[PeriodicActivity|EString])? "}"
		public Group getGroup() { return cGroup; }

		//{exploitation::Elevage}
		public Action getElevageAction_0() { return cElevageAction_0; }

		//"Elevage"
		public Keyword getElevageKeyword_1() { return cElevageKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("activity" activity+=[PeriodicActivity|EString])?
		public Group getGroup_3() { return cGroup_3; }

		//"activity"
		public Keyword getActivityKeyword_3_0() { return cActivityKeyword_3_0; }

		//activity+=[PeriodicActivity|EString]
		public Assignment getActivityAssignment_3_1() { return cActivityAssignment_3_1; }

		//[PeriodicActivity|EString]
		public CrossReference getActivityPeriodicActivityCrossReference_3_1_0() { return cActivityPeriodicActivityCrossReference_3_1_0; }

		//EString
		public RuleCall getActivityPeriodicActivityEStringParserRuleCall_3_1_0_1() { return cActivityPeriodicActivityEStringParserRuleCall_3_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class CultureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Culture");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cCultureAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cCultureKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cActivityKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cActivityAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cActivityPeriodicActivityCrossReference_3_1_0 = (CrossReference)cActivityAssignment_3_1.eContents().get(0);
		private final RuleCall cActivityPeriodicActivityEStringParserRuleCall_3_1_0_1 = (RuleCall)cActivityPeriodicActivityCrossReference_3_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Culture returns exploitation::Culture:
		//	{exploitation::Culture} "Culture" "{" ("activity" activity+=[PeriodicActivity|EString])? "}";
		public ParserRule getRule() { return rule; }

		//{exploitation::Culture} "Culture" "{" ("activity" activity+=[PeriodicActivity|EString])? "}"
		public Group getGroup() { return cGroup; }

		//{exploitation::Culture}
		public Action getCultureAction_0() { return cCultureAction_0; }

		//"Culture"
		public Keyword getCultureKeyword_1() { return cCultureKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("activity" activity+=[PeriodicActivity|EString])?
		public Group getGroup_3() { return cGroup_3; }

		//"activity"
		public Keyword getActivityKeyword_3_0() { return cActivityKeyword_3_0; }

		//activity+=[PeriodicActivity|EString]
		public Assignment getActivityAssignment_3_1() { return cActivityAssignment_3_1; }

		//[PeriodicActivity|EString]
		public CrossReference getActivityPeriodicActivityCrossReference_3_1_0() { return cActivityPeriodicActivityCrossReference_3_1_0; }

		//EString
		public RuleCall getActivityPeriodicActivityEStringParserRuleCall_3_1_0_1() { return cActivityPeriodicActivityEStringParserRuleCall_3_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	
	
	public class PeriodicityElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "Periodicity");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cMonthEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cMonthMonthsKeyword_0_0 = (Keyword)cMonthEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cDaysEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cDaysDaysKeyword_1_0 = (Keyword)cDaysEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cWeeksEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cWeeksWeeksKeyword_2_0 = (Keyword)cWeeksEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cYearsEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cYearsYearsKeyword_3_0 = (Keyword)cYearsEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cHoursEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cHoursHoursKeyword_4_0 = (Keyword)cHoursEnumLiteralDeclaration_4.eContents().get(0);
		
		//enum Periodicity returns periodicity:
		//	month="months" | days | weeks | years | hours;
		public EnumRule getRule() { return rule; }

		//month="months" | days | weeks | years | hours
		public Alternatives getAlternatives() { return cAlternatives; }

		//month="months"
		public EnumLiteralDeclaration getMonthEnumLiteralDeclaration_0() { return cMonthEnumLiteralDeclaration_0; }

		//"months"
		public Keyword getMonthMonthsKeyword_0_0() { return cMonthMonthsKeyword_0_0; }

		//days
		public EnumLiteralDeclaration getDaysEnumLiteralDeclaration_1() { return cDaysEnumLiteralDeclaration_1; }

		//"days"
		public Keyword getDaysDaysKeyword_1_0() { return cDaysDaysKeyword_1_0; }

		//weeks
		public EnumLiteralDeclaration getWeeksEnumLiteralDeclaration_2() { return cWeeksEnumLiteralDeclaration_2; }

		//"weeks"
		public Keyword getWeeksWeeksKeyword_2_0() { return cWeeksWeeksKeyword_2_0; }

		//years
		public EnumLiteralDeclaration getYearsEnumLiteralDeclaration_3() { return cYearsEnumLiteralDeclaration_3; }

		//"years"
		public Keyword getYearsYearsKeyword_3_0() { return cYearsYearsKeyword_3_0; }

		//hours
		public EnumLiteralDeclaration getHoursEnumLiteralDeclaration_4() { return cHoursEnumLiteralDeclaration_4; }

		//"hours"
		public Keyword getHoursHoursKeyword_4_0() { return cHoursHoursKeyword_4_0; }
	}

	public class MonthElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "Month");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cJanuaryEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cJanuaryJanuaryKeyword_0_0 = (Keyword)cJanuaryEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cFebruaryEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cFebruaryFebruaryKeyword_1_0 = (Keyword)cFebruaryEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cMarchEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cMarchMarchKeyword_2_0 = (Keyword)cMarchEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cAprilEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cAprilAprilKeyword_3_0 = (Keyword)cAprilEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cMayEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cMayMayKeyword_4_0 = (Keyword)cMayEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cJuneEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cJuneJuneKeyword_5_0 = (Keyword)cJuneEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cJulyEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cJulyJulyKeyword_6_0 = (Keyword)cJulyEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cAugustEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cAugustAugustKeyword_7_0 = (Keyword)cAugustEnumLiteralDeclaration_7.eContents().get(0);
		private final EnumLiteralDeclaration cSeptemberEnumLiteralDeclaration_8 = (EnumLiteralDeclaration)cAlternatives.eContents().get(8);
		private final Keyword cSeptemberSeptemberKeyword_8_0 = (Keyword)cSeptemberEnumLiteralDeclaration_8.eContents().get(0);
		private final EnumLiteralDeclaration cOctoberEnumLiteralDeclaration_9 = (EnumLiteralDeclaration)cAlternatives.eContents().get(9);
		private final Keyword cOctoberOctoberKeyword_9_0 = (Keyword)cOctoberEnumLiteralDeclaration_9.eContents().get(0);
		private final EnumLiteralDeclaration cNovemberEnumLiteralDeclaration_10 = (EnumLiteralDeclaration)cAlternatives.eContents().get(10);
		private final Keyword cNovemberNovemberKeyword_10_0 = (Keyword)cNovemberEnumLiteralDeclaration_10.eContents().get(0);
		private final EnumLiteralDeclaration cDecemberEnumLiteralDeclaration_11 = (EnumLiteralDeclaration)cAlternatives.eContents().get(11);
		private final Keyword cDecemberDecemberKeyword_11_0 = (Keyword)cDecemberEnumLiteralDeclaration_11.eContents().get(0);
		
		//enum Month:
		//	january | february | march | april | may | june | july | august | september | october | november | december;
		public EnumRule getRule() { return rule; }

		//january | february | march | april | may | june | july | august | september | october | november | december
		public Alternatives getAlternatives() { return cAlternatives; }

		//january
		public EnumLiteralDeclaration getJanuaryEnumLiteralDeclaration_0() { return cJanuaryEnumLiteralDeclaration_0; }

		//"january"
		public Keyword getJanuaryJanuaryKeyword_0_0() { return cJanuaryJanuaryKeyword_0_0; }

		//february
		public EnumLiteralDeclaration getFebruaryEnumLiteralDeclaration_1() { return cFebruaryEnumLiteralDeclaration_1; }

		//"february"
		public Keyword getFebruaryFebruaryKeyword_1_0() { return cFebruaryFebruaryKeyword_1_0; }

		//march
		public EnumLiteralDeclaration getMarchEnumLiteralDeclaration_2() { return cMarchEnumLiteralDeclaration_2; }

		//"march"
		public Keyword getMarchMarchKeyword_2_0() { return cMarchMarchKeyword_2_0; }

		//april
		public EnumLiteralDeclaration getAprilEnumLiteralDeclaration_3() { return cAprilEnumLiteralDeclaration_3; }

		//"april"
		public Keyword getAprilAprilKeyword_3_0() { return cAprilAprilKeyword_3_0; }

		//may
		public EnumLiteralDeclaration getMayEnumLiteralDeclaration_4() { return cMayEnumLiteralDeclaration_4; }

		//"may"
		public Keyword getMayMayKeyword_4_0() { return cMayMayKeyword_4_0; }

		//june
		public EnumLiteralDeclaration getJuneEnumLiteralDeclaration_5() { return cJuneEnumLiteralDeclaration_5; }

		//"june"
		public Keyword getJuneJuneKeyword_5_0() { return cJuneJuneKeyword_5_0; }

		//july
		public EnumLiteralDeclaration getJulyEnumLiteralDeclaration_6() { return cJulyEnumLiteralDeclaration_6; }

		//"july"
		public Keyword getJulyJulyKeyword_6_0() { return cJulyJulyKeyword_6_0; }

		//august
		public EnumLiteralDeclaration getAugustEnumLiteralDeclaration_7() { return cAugustEnumLiteralDeclaration_7; }

		//"august"
		public Keyword getAugustAugustKeyword_7_0() { return cAugustAugustKeyword_7_0; }

		//september
		public EnumLiteralDeclaration getSeptemberEnumLiteralDeclaration_8() { return cSeptemberEnumLiteralDeclaration_8; }

		//"september"
		public Keyword getSeptemberSeptemberKeyword_8_0() { return cSeptemberSeptemberKeyword_8_0; }

		//october
		public EnumLiteralDeclaration getOctoberEnumLiteralDeclaration_9() { return cOctoberEnumLiteralDeclaration_9; }

		//"october"
		public Keyword getOctoberOctoberKeyword_9_0() { return cOctoberOctoberKeyword_9_0; }

		//november
		public EnumLiteralDeclaration getNovemberEnumLiteralDeclaration_10() { return cNovemberEnumLiteralDeclaration_10; }

		//"november"
		public Keyword getNovemberNovemberKeyword_10_0() { return cNovemberNovemberKeyword_10_0; }

		//december
		public EnumLiteralDeclaration getDecemberEnumLiteralDeclaration_11() { return cDecemberEnumLiteralDeclaration_11; }

		//"december"
		public Keyword getDecemberDecemberKeyword_11_0() { return cDecemberDecemberKeyword_11_0; }
	}
	
	private ModelElements pModel;
	private PeriodicActivityElements pPeriodicActivity;
	private PeriodicityElements unknownRulePeriodicity;
	private MonthElements unknownRuleMonth;
	private AtelierElements pAtelier;
	private DateElements pDate;
	private ResAllocationElements pResAllocation;
	private EStringElements pEString;
	private RuleElements pRule;
	private Atelier_ImplElements pAtelier_Impl;
	private EIntElements pEInt;
	private RessourceTypeElements pRessourceType;
	private PredicateElements pPredicate;
	private ElevageElements pElevage;
	private CultureElements pCulture;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public ActGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.activity.Act".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//	{Model} "Categorie" name=EString "{" activity+=PeriodicActivity* "}";
	public ModelElements getModelAccess() {
		return (pModel != null) ? pModel : (pModel = new ModelElements());
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}

	//PeriodicActivity:
	//	{PeriodicActivity} "PeriodicActivity" name=EString "{" ("workshop" atelier=[exploitation::Atelier|EString] ",")?
	//	"from" start=Date "to" end=Date "," ("every" frequency=EInt? periodicityType=Periodicity ",")? ("allocate" "{"
	//	resAllocation+=ResAllocation ("," resAllocation+=ResAllocation)* "}" ",")? ("rules" "{" rule+=Rule ("," rule+=Rule)*
	//	"}")? "}";
	public PeriodicActivityElements getPeriodicActivityAccess() {
		return (pPeriodicActivity != null) ? pPeriodicActivity : (pPeriodicActivity = new PeriodicActivityElements());
	}
	
	public ParserRule getPeriodicActivityRule() {
		return getPeriodicActivityAccess().getRule();
	}

	//enum Periodicity returns periodicity:
	//	month="months" | days | weeks | years | hours;
	public PeriodicityElements getPeriodicityAccess() {
		return (unknownRulePeriodicity != null) ? unknownRulePeriodicity : (unknownRulePeriodicity = new PeriodicityElements());
	}
	
	public EnumRule getPeriodicityRule() {
		return getPeriodicityAccess().getRule();
	}

	//enum Month:
	//	january | february | march | april | may | june | july | august | september | october | november | december;
	public MonthElements getMonthAccess() {
		return (unknownRuleMonth != null) ? unknownRuleMonth : (unknownRuleMonth = new MonthElements());
	}
	
	public EnumRule getMonthRule() {
		return getMonthAccess().getRule();
	}

	//Atelier returns exploitation::Atelier:
	//	Atelier_Impl | Elevage | Culture;
	public AtelierElements getAtelierAccess() {
		return (pAtelier != null) ? pAtelier : (pAtelier = new AtelierElements());
	}
	
	public ParserRule getAtelierRule() {
		return getAtelierAccess().getRule();
	}

	//Date:
	//	{Date} day=EInt month=Month;
	public DateElements getDateAccess() {
		return (pDate != null) ? pDate : (pDate = new DateElements());
	}
	
	public ParserRule getDateRule() {
		return getDateAccess().getRule();
	}

	//ResAllocation returns RessourceAllocation:
	//	{RessourceAllocation} "reserve" ressource=[exploitation::Ressource|EString] "for" duration=EInt
	//	periodicityType=Periodicity;
	public ResAllocationElements getResAllocationAccess() {
		return (pResAllocation != null) ? pResAllocation : (pResAllocation = new ResAllocationElements());
	}
	
	public ParserRule getResAllocationRule() {
		return getResAllocationAccess().getRule();
	}

	//EString returns ecore::EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return (pEString != null) ? pEString : (pEString = new EStringElements());
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	//Rule:
	//	{Rule} ("pre" pre+=Predicate ("," "pre" pre+=Predicate)*)?;
	public RuleElements getRuleAccess() {
		return (pRule != null) ? pRule : (pRule = new RuleElements());
	}
	
	public ParserRule getRuleRule() {
		return getRuleAccess().getRule();
	}

	//Atelier_Impl returns exploitation::Atelier:
	//	{exploitation::Atelier} "Atelier" "{" ("activity" activity+=[PeriodicActivity|EString])? "}";
	public Atelier_ImplElements getAtelier_ImplAccess() {
		return (pAtelier_Impl != null) ? pAtelier_Impl : (pAtelier_Impl = new Atelier_ImplElements());
	}
	
	public ParserRule getAtelier_ImplRule() {
		return getAtelier_ImplAccess().getRule();
	}

	//EInt returns ecore::EInt:
	//	"-"? INT;
	public EIntElements getEIntAccess() {
		return (pEInt != null) ? pEInt : (pEInt = new EIntElements());
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}

	//RessourceType returns exploitation::RessourceType:
	//	{exploitation::RessourceType} "RessourceType" name=EString;
	public RessourceTypeElements getRessourceTypeAccess() {
		return (pRessourceType != null) ? pRessourceType : (pRessourceType = new RessourceTypeElements());
	}
	
	public ParserRule getRessourceTypeRule() {
		return getRessourceTypeAccess().getRule();
	}

	//Predicate returns Predicat:
	//	{Predicat} EString;
	public PredicateElements getPredicateAccess() {
		return (pPredicate != null) ? pPredicate : (pPredicate = new PredicateElements());
	}
	
	public ParserRule getPredicateRule() {
		return getPredicateAccess().getRule();
	}

	//Elevage returns exploitation::Elevage:
	//	{exploitation::Elevage} "Elevage" "{" ("activity" activity+=[PeriodicActivity|EString])? "}";
	public ElevageElements getElevageAccess() {
		return (pElevage != null) ? pElevage : (pElevage = new ElevageElements());
	}
	
	public ParserRule getElevageRule() {
		return getElevageAccess().getRule();
	}

	//Culture returns exploitation::Culture:
	//	{exploitation::Culture} "Culture" "{" ("activity" activity+=[PeriodicActivity|EString])? "}";
	public CultureElements getCultureAccess() {
		return (pCulture != null) ? pCulture : (pCulture = new CultureElements());
	}
	
	public ParserRule getCultureRule() {
		return getCultureAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
