/**
 * generated by Xtext
 */
package org.xtext.activity.serializer;

import org.xtext.activity.serializer.AbstractActSyntacticSequencer;

@SuppressWarnings("all")
public class ActSyntacticSequencer extends AbstractActSyntacticSequencer {
}
