/**
 * generated by Xtext
 */
package org.xtext.activity.serializer;

import org.xtext.activity.serializer.AbstractActSemanticSequencer;

@SuppressWarnings("all")
public class ActSemanticSequencer extends AbstractActSemanticSequencer {
}
