/*
 * generated by Xtext
 */
package org.xtext.activity.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.activity.ui.internal.ActActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ActExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ActActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ActActivator.getInstance().getInjector(ActActivator.ORG_XTEXT_ACTIVITY_ACT);
	}
	
}
