/*
 * generated by Xtext
 */
package org.xtext.activity;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ActRuntimeModule extends org.xtext.activity.AbstractActRuntimeModule {

}
