/*
* generated by Xtext
*/
package org.xtext.activity;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ActStandaloneSetup extends ActStandaloneSetupGenerated{

	public static void doSetup() {
		new ActStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

