/**
 * generated by Xtext
 */
package org.xtext.activity.ui.contentassist;

import org.xtext.activity.ui.contentassist.AbstractActProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class ActProposalProvider extends AbstractActProposalProvider {
}
