/*
 * generated by Xtext
 */
package org.xtext.activity.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractActValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://activity/1.0"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://exploitation/1.0"));
		return result;
	}
}
