/*
 * generated by Xtext
 */
package org.xtext.launcher;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class StartRuntimeModule extends org.xtext.launcher.AbstractStartRuntimeModule {

}
