/**
 * generated by Xtext
 */
package org.xtext.activity.validation;

import org.xtext.activity.validation.AbstractActValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class ActValidator extends AbstractActValidator {
}
