<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="activity" nsURI="http://activity/1.0" nsPrefix="activity">
  <eClassifiers xsi:type="ecore:EClass" name="ActivityPeriodic">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" lowerBound="1" eType="#//Date"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" lowerBound="1" eType="#//Date"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" upperBound="-1" eType="#//Rule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resAllocation" upperBound="-1"
        eType="#//RessourceAllocation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="atelier" eType="ecore:EClass exploitation.ecore#//Atelier"
        eOpposite="exploitation.ecore#//Atelier/activity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="periodicity"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Month"/>
  <eClassifiers xsi:type="ecore:EClass" name="Date">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="day" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" upperBound="-1"
        eType="#//ActivityPeriodic" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ressourceType" upperBound="-1"
        eType="ecore:EClass exploitation.ecore#//RessourceType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RessourceAllocation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duree" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ressource" lowerBound="1"
        eType="ecore:EClass exploitation.ecore#//Ressource" eOpposite="exploitation.ecore#//Ressource/resAllocation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pre" upperBound="-1" eType="#//Predicat"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Predicat"/>
  <eClassifiers xsi:type="ecore:EClass" name="EClass0"/>
</ecore:EPackage>
