<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="activity" nsURI="http://activity/1.0" nsPrefix="activity">
  <eClassifiers xsi:type="ecore:EClass" name="PeriodicActivity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" lowerBound="1" eType="#//Date"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" lowerBound="1" eType="#//Date"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" upperBound="-1" eType="#//Rule"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resAllocation" upperBound="-1"
        eType="#//RessourceAllocation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="atelier" eType="ecore:EClass exploitation.ecore#//Atelier"
        eOpposite="exploitation.ecore#//Atelier/activity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="periodicityType" eType="#//periodicity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="frequency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="periodicity" instanceTypeName="Periodicity">
    <eLiterals name="years"/>
    <eLiterals name="month" value="1" literal="months"/>
    <eLiterals name="weeks" value="2"/>
    <eLiterals name="days" value="3"/>
    <eLiterals name="hours" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Month">
    <eLiterals name="january" value="1"/>
    <eLiterals name="february" value="2"/>
    <eLiterals name="march" value="3"/>
    <eLiterals name="april" value="4"/>
    <eLiterals name="may" value="5"/>
    <eLiterals name="june" value="6"/>
    <eLiterals name="july" value="7"/>
    <eLiterals name="august" value="8"/>
    <eLiterals name="september" value="9"/>
    <eLiterals name="october" value="10"/>
    <eLiterals name="november" value="11"/>
    <eLiterals name="december" value="12"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Date">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="day" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="month" eType="#//Month"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" upperBound="-1"
        eType="#//PeriodicActivity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ressourceType" upperBound="-1"
        eType="ecore:EClass exploitation.ecore#//RessourceType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RessourceAllocation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ressource" lowerBound="1"
        eType="ecore:EClass exploitation.ecore#//Ressource" eOpposite="exploitation.ecore#//Ressource/resAllocation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="periodicityType" eType="#//periodicity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rule"/>
  <eClassifiers xsi:type="ecore:EClass" name="Predicat" eSuperTypes="#//Rule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="date" eType="#//Date" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CheckDoneActivity" eSuperTypes="#//Predicat">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elapsedTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" eType="#//CheckDoneActivity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activityToValidate" eType="#//PeriodicActivity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="periodicityType" eType="#//periodicity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NoRain" eSuperTypes="#//Predicat">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elapsedTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="periodicityType" eType="#//periodicity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryExpression" eSuperTypes="#//Rule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Rule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Rule"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ope" eType="#//BinaryExpressionType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Weather" abstract="true" eSuperTypes="#//Predicat">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comparator" eType="#//ComparatorType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ComparatorType">
    <eLiterals name="inferior"/>
    <eLiterals name="inferiorOrEqual" value="1"/>
    <eLiterals name="equal" value="2"/>
    <eLiterals name="different" value="3"/>
    <eLiterals name="superior" value="4"/>
    <eLiterals name="superiorOrEqual" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Temperature" eSuperTypes="#//Weather">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvapoTranspiration" eSuperTypes="#//Weather">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Precipitation" eSuperTypes="#//Weather">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rayonnement" eSuperTypes="#//Weather">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BinaryExpressionType">
    <eLiterals name="AND"/>
    <eLiterals name="OR" value="1"/>
    <eLiterals name="XOR" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GrainStateEnum">
    <eLiterals name="MATURE"/>
    <eLiterals name="IMMATURE" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GrainState" eSuperTypes="#//Predicat">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="#//GrainStateEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Launcher">
    <eStructuralFeatures xsi:type="ecore:EReference" name="begin" lowerBound="1" eType="#//Date"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" lowerBound="1" eType="#//Date"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qMax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantityOfWater" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
