/*
* generated by Xtext
*/
package org.xtext.launcher.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.launcher.services.StartGrammarAccess;

public class StartParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private StartGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.launcher.parser.antlr.internal.InternalStartParser createParser(XtextTokenStream stream) {
		return new org.xtext.launcher.parser.antlr.internal.InternalStartParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Launcher";
	}
	
	public StartGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(StartGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
